"""Phase 6 集中阈值，CLI中不得散落魔法数字。"""

CAPTURE_DURATION_RATIO_PASS = 0.95
TELEMETRY_HZ_PASS_MIN = 9.5
TELEMETRY_HZ_PASS_MAX = 10.5
ACCEL_MAGNITUDE_PASS_MIN_MG = 900.0
ACCEL_MAGNITUDE_PASS_MAX_MG = 1100.0
ACCEL_MAGNITUDE_WARN_MIN_MG = 800.0
ACCEL_MAGNITUDE_WARN_MAX_MG = 1200.0
EXPECTED_PROTOCOL_VERSION = 1
MAX_REPORT_ROWS_WARNING = 1_000_000
ATTITUDE_MOVEMENT_PASS_DEG = 5.0
