#ifndef PROTOCOL_CONSTANTS_H
#define PROTOCOL_CONSTANTS_H

#include <stdint.h>

#define PROTOCOL_SOF1 0xA5U
#define PROTOCOL_SOF2 0x5AU
#define PROTOCOL_VERSION 0x01U
#define PROTOCOL_MAX_PAYLOAD_SIZE 128U
#define PROTOCOL_FIXED_SIZE 11U
#define PROTOCOL_MAX_FRAME_SIZE (PROTOCOL_FIXED_SIZE + PROTOCOL_MAX_PAYLOAD_SIZE)
#define PROTOCOL_RX_STORAGE_SIZE 256U
#define PROTOCOL_RX_BUDGET_PER_RUN 32U
#define PROTOCOL_PARSE_BUDGET_PER_RUN 64U

typedef enum
{
    PROTOCOL_TYPE_PING = 0x01,
    PROTOCOL_TYPE_GET_DEVICE_INFO = 0x02,
    PROTOCOL_TYPE_GET_STATUS = 0x03,
    PROTOCOL_TYPE_GET_CONFIG = 0x04,
    PROTOCOL_TYPE_SET_CONFIG = 0x05,
    PROTOCOL_TYPE_START_CALIBRATION = 0x06,
    PROTOCOL_TYPE_SET_STREAM_STATE = 0x07,
    PROTOCOL_TYPE_GET_LATEST_MOTION = 0x08,
    PROTOCOL_TYPE_MOTION_TELEMETRY = 0x20,
    PROTOCOL_TYPE_HEALTH_TELEMETRY = 0x21,
    PROTOCOL_TYPE_EVENT_TELEMETRY = 0x22,
    PROTOCOL_TYPE_COMMAND_RESPONSE = 0x80
} ProtocolMessageType_t;

typedef enum
{
    PROTOCOL_STATUS_OK = 0,
    PROTOCOL_STATUS_INVALID_COMMAND,
    PROTOCOL_STATUS_INVALID_LENGTH,
    PROTOCOL_STATUS_INVALID_VALUE,
    PROTOCOL_STATUS_NOT_READY,
    PROTOCOL_STATUS_BUSY,
    PROTOCOL_STATUS_UNSUPPORTED,
    PROTOCOL_STATUS_INTERNAL_ERROR
} ProtocolStatusCode_t;

#endif /* PROTOCOL_CONSTANTS_H */
