#ifndef PROTOCOL_CONSTANTS_H
#define PROTOCOL_CONSTANTS_H

#include <stdint.h>

#define PROTOCOL_SOF1 0xA5U
#define PROTOCOL_SOF2 0x5AU
#define PROTOCOL_VERSION 0x01U
#define PROTOCOL_MAX_PAYLOAD_SIZE 128U
#define PROTOCOL_FIXED_SIZE 11U
#define PROTOCOL_MAX_FRAME_SIZE (PROTOCOL_FIXED_SIZE + PROTOCOL_MAX_PAYLOAD_SIZE)
#define PROTOCOL_RX_STORAGE_SIZE 256U
#define PROTOCOL_RX_BUDGET_PER_RUN 32U
#define PROTOCOL_PARSE_BUDGET_PER_RUN 64U

typedef enum
{
    PROTOCOL_TYPE_PING = 0x01,
    PROTOCOL_TYPE_GET_DEVICE_INFO = 0x02,
    PROTOCOL_TYPE_GET_STATUS = 0x03,
    PROTOCOL_TYPE_GET_CONFIG = 0x04,
    PROTOCOL_TYPE_SET_CONFIG = 0x05,
    PROTOCOL_TYPE_START_CALIBRATION = 0x06,
    PROTOCOL_TYPE_SET_STREAM_STATE = 0x07,
    PROTOCOL_TYPE_GET_LATEST_MOTION = 0x08,
    PROTOCOL_TYPE_ACTUATOR_GET_STATUS = 0x09,
    PROTOCOL_TYPE_ACTUATOR_ARM = 0x0A,
    PROTOCOL_TYPE_ACTUATOR_DISARM = 0x0B,
    PROTOCOL_TYPE_ACTUATOR_SET_TARGET = 0x0C,
    PROTOCOL_TYPE_ACTUATOR_CENTER = 0x0D,
    PROTOCOL_TYPE_ACTUATOR_ESTOP = 0x0E,
    PROTOCOL_TYPE_ACTUATOR_SET_RAW_PULSE = 0x0F,
    PROTOCOL_TYPE_CONTROL_GET_STATUS = 0x10,
    PROTOCOL_TYPE_CONTROL_ENABLE = 0x11,
    PROTOCOL_TYPE_CONTROL_DISABLE = 0x12,
    PROTOCOL_TYPE_CONTROL_SET_ZERO = 0x13,
    PROTOCOL_TYPE_CONTROL_SET_AXIS = 0x14,
    PROTOCOL_TYPE_CONTROL_SET_DIRECTION = 0x15,
    PROTOCOL_TYPE_CONTROL_GET_PID = 0x16,
    PROTOCOL_TYPE_CONTROL_SET_PID = 0x17,
    PROTOCOL_TYPE_CONTROL_SET_DEADBAND = 0x18,
    PROTOCOL_TYPE_MOTION_TELEMETRY = 0x20,
    PROTOCOL_TYPE_HEALTH_TELEMETRY = 0x21,
    PROTOCOL_TYPE_EVENT_TELEMETRY = 0x22,
    PROTOCOL_TYPE_ACTUATOR_TELEMETRY = 0x23,
    PROTOCOL_TYPE_CONTROL_TELEMETRY = 0x24,
    PROTOCOL_TYPE_COMMAND_RESPONSE = 0x80
} ProtocolMessageType_t;

typedef enum
{
    PROTOCOL_STATUS_OK = 0,
    PROTOCOL_STATUS_INVALID_COMMAND,
    PROTOCOL_STATUS_INVALID_LENGTH,
    PROTOCOL_STATUS_INVALID_VALUE,
    PROTOCOL_STATUS_NOT_READY,
    PROTOCOL_STATUS_BUSY,
    PROTOCOL_STATUS_UNSUPPORTED,
    PROTOCOL_STATUS_INTERNAL_ERROR
} ProtocolStatusCode_t;

#endif /* PROTOCOL_CONSTANTS_H */
